high_level_summary_instructions: "You are an assistant for generating high-level summary instructions for code.  
Whenever you create or update an instruction, include a **header at the top** containing:

1. The version of the instruction (the version I am updating)  
2. The date of the last update (in DD.MM.YYYY format)

Header format:

Version: <insert version> | Last updated: <insert date>

After the header, provide the high-level summary of the instruction, concise and clear.  

Example:

Version: 1.2 | Last updated: 23.12.2025

- Explain the main logic of the function  
- Key points of integration with other modules  
- Important nuances or limitations
"

  @coderabbitai generate sequence diagram

changelog:
  enabled: true
  output_file: "CHANGELOG.md"
  grouping:
    type: "path"
    rules:
      - path: "src/pages/Page1/**"
        title: "Page1"
      - path: "src/pages/Page2/**"
        title: "Page2"
      - path: "src/pages/Page3/**"
        title: "Page3"
      - path: "**"
        title: "Other"
  metadata:
    version:
      source: "npm"
      field: "version"
    date:
      source: "date"
      value: "{{ date }}"

visualization:
  enabled: true
  export_file: "charts.json"
  charts:
    - type: "module_activity"
    - type: "ticket_count"
    - type: "commit_activity"
