
reviews:
  path_instructions:
    - path: "src/pages/**"
      instructions: "Name this changes just by page folder, like src/pages/Page1 convert to Page1 and description."
  high_level_summary_instructions: "You are an assistant for generating high-level summary instructions for code.  
Whenever you create or update an instruction, include a **header at the top** containing:

1. The version of the instruction (the version I am updating)  
2. The date of the last update (in DD.MM.YYYY format)

Header format:

Version: <insert version> | Last updated: <insert date>

After the header, provide the high-level summary of the instruction, concise and clear.  

Example:

Version: 1.2 | Last updated: 23.12.2025

- Explain the main logic of the function  
- Key points of integration with other modules  
- Important nuances or limitations
"